name: Rust

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run:
                - cargo build --verbose
	            - cargo build --verbose --all-features
	            - cargo build --verbose --tests
	            - cargo build --verbose --tests --all-features

            - name: Check
              run:
                - cargo check --verbose
	            - cargo check --verbose --all-features
	            - cargo check --verbose --tests
	            - cargo check --verbose --tests --all-features
