name: Rust

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cargo build --verbose
            - run: cargo build --verbose --all-features
            - run: cargo build --verbose --tests
            - run: cargo build --verbose --tests --all-features

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cargo check --verbose
            - run: cargo check --verbose --all-features
            - run: cargo check --verbose --tests
            - run: cargo check --verbose --tests --all-features
